routes/web.php
<?php

use App\Http\Controllers\Dashboard;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    Route::get('/', function () {
        return view('dashboard');
    });

    Route::get('/logout', function () {
        return view('dashboard');
    });

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/users', function () {
        return view('dashboard');
    })->name('users');

    Route::get('/terms', function () {
        return view('dashboard');
    })->name('terms');

    Route::get('accepted-terms', function () {
        return view('terms', [
            'terms' => Auth::user()->acceptedTermToHtml()
        ]);
    })->name('accepted-terms');

    Route::get('accept-terms', function () {
        Auth::user()->acceptNewestTerms();
        return Redirect::back()->with('success', 'Terms accepted.');
    })->name('accept-terms');

});

app/Models/Term.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Term extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'body',
        'published_at',
    ];

    public function getPublishedColorAttribute()
    {
        return $this->published_at ? 'green' : 'gray';
    }

    public function getDateForHumansAttribute()
    {
        return Carbon::parse($this->published_at)->format('Y M d h:m:s');
    }

    public static function latestPublishedDate()
    {
        return Term::orderBy('published_at', 'desc')->first()?->published_at ?? null;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use DateTime;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Jetstream\HasProfilePhoto;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Date;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'password',
        'terms_accepted_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function getEmailVerifiedColorAttribute()
    {
        return $this->email_verified_at ? 'green' : 'gray';
    }

    public function getDateForHumansAttribute()
    {
        return Carbon::parse($this->email_verified_at)->format('Y M d h:m:s');
    }

    public function unVerify()
    {
        $this->email_verified_at = null;
        $this->update();
    }

    public function termOutdated()
    {
        return (Term::latestPublishedDate() > $this->terms_accepted_at); // if published term is newer than user's consent
    }

    public function getAcceptedTerm () {
        return Term::whereNotNull('published_at')->where('published_at', '<=', $this->terms_accepted_at)->orderBy('published_at', 'desc')->first();
    }

    public function acceptedTermToHtml()
    {
        $accepted_terms = Term::whereNotNull('published_at')
            ->where('published_at', '<=', $this->terms_accepted_at ?? date('YY mm dd hh:mm:ss', null))->orderBy('published_at', 'desc')->first();
        return Str::markdown($accepted_terms ? $accepted_terms->body : '<div class="font-semibold text-center">No terms accepted yet!</div>');
    }

    public function acceptNewestTerms()
    {
        $this->terms_accepted_at = now();
        $this->save();
    }
}

app/Http/Livewire/Terms.php
<?php

namespace App\Http\Livewire;

use Exception;
use App\Models\Term;
use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
use Illuminate\Validation\Rule;
use App\Notifications\TermsUpdated;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Notification;

class Terms extends Component
{

    use WithPagination;

    public $search = '';
    public $sortField;
    public $sortDirection = 'desc';
    public $editedTerm; // array containing edited term's data
    public $newTerm; // array containing new term's data

    protected $queryString = ['sortField', 'sortDirection'];

    protected $messages = [
        'editedTerm.name.required' => 'Term name is required.',
        'editedTerm.name.string' => 'Term name must be a string.',
        'editedTerm.name.max:255' => 'Term name can\'t be longer than 255 characters.',
        'editedTerm.name.unique' => 'Name already in use.',
        'editedTerm.name.body' => 'Term body is required.',
        'editedTerm.name.body' => 'Term body must be a string.',
        'editedTerm.body.max:4294967295' => 'Term body can\'t be longer than 4294967295 characters.',
    ];

    protected function rules()
    {
        return [
            'editedTerm.name' => ['required', 'string', 'max:255', Rule::unique('terms', 'name')->ignore($this->editedTerm['id'])],
            'editedTerm.body' => ['required', 'string', 'max:4294967295'],
        ];
    }

    public function boot()
    {
        $this->resetEdit();
        $this->resetNew();
    }

    private function resetEdit()
    {
        $this->editedTerm = [
            'id' => null,
            'name' => null,
            'body' => null,
            'published_at' => null,
        ];
    }

    private function resetNew()
    {
        $this->newTerm = [
            'id' => null,
            'name' => null,
            'body' => null,
            'published_at' => null,
        ];
    }

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc';
        } else {
            $this->sortDirection = 'asc';
        }
        $this->sortField = $field;
    }

    public function publishTerm($termid)
    {
        $term = Term::find($termid);

        if ($term->published_at !== null) {
            return;
            //Redirect::to("/terms")->with('failure', 'Published terms cannot be republished.');
        }

        $term->published_at = now();
        $term->save();

        Notification::send(User::all(), new TermsUpdated());

        Storage::disk('terms')->put('terms.md', $term->body);

        Redirect::to("/terms")->with('success', 'Term published.');
    }

    public function addTerm()
    {
        $term = new Term;
        $term->name = $this->newTerm['name'];
        $term->body = $this->newTerm['body'];
        $term->save();
        $this->resetNew();
    }

    public function editTerm($termid)
    {
        $term = Term::find($termid);
        $this->resetEdit();
        $this->editedTerm['id'] = $term->id;
        $this->editedTerm['name'] = $term->name;
        $this->editedTerm['body'] = $term->body;
    }

    public function saveTerm($termid)
    {

        $term = Term::find($termid);

        if ($term->published_at !== null) {
            return;
            //Redirect::to("/terms")->with('failure', 'Published terms cannot be edited.');
        }

        if ($this->editedTerm['id'] == $termid) {

            $this->validate();

            $term->name = $this->editedTerm['name'];
            $term->body = $this->editedTerm['body'];
            $term->save();

            $this->resetEdit();

            //Redirect::to("/terms")->with('success', 'Term updated.');
        }
    }

    public function delete($termid)
    {

        $term = Term::find($termid);

        if ($term->published_at !== null) {
            return;
            //Redirect::to("/terms")->with('failure', 'Published terms cannot be deleted.');
        }

        Term::find($termid)->delete();

        //Redirect::to("/users")->with('success', 'User deleted.');
    }

    public function render()
    {
        if ($this->sortField === null) {
            $this->sortField = 'published_at';
        }

        return view('livewire.terms', [
            'terms' => Term::where('name', 'like', '%' . $this->search . '%')
                ->orWhere('body', 'like', '%' . $this->search . '%')
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate(5)
        ]);
    }
}

app/Http/Livewire/Users.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
use Illuminate\Validation\Rule;
use Laravel\Jetstream\Jetstream;
use Illuminate\Auth\MustVerifyEmail;
use Tests\Feature\EmailVerificationTest;
use App\Actions\Fortify\UpdateUserProfileInformation;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Support\Facades\Redirect;
use Laravel\Fortify\Http\Controllers\EmailVerificationNotificationController;

class Users extends Component
{
    use WithPagination;

    public $search = '';
    public $sortField;
    public $sortDirection = 'asc';
    public $editedUser; // array containing edited user's data

    protected $queryString = ['sortField', 'sortDirection'];

    protected $messages = [
        'editedUser.name.required' => 'User name is required.',
        'editedUser.name.string' => 'User name must be a string.',
        'editedUser.name.max:255' => 'User name can\'t be longer than 255 characters',
        'editedUser.email.required' => 'User email is required.',
        'editedUser.email.email' => 'User email must be a valid email address.',
        'editedUser.email.unique' => 'Somebody has the same email.',
        'editedUser.phone.required' => 'Phone number is required.',
        'editedUser.phone.string' => 'Phone number must be a string.',
        'editedUser.phone.max:255' => 'Phone number can\'t be longer than 255 characters',
    ];

    protected function rules()
    {
        return [
            'editedUser.name' => ['required', 'string', 'max:255'],
            'editedUser.email' => ['required', 'email', Rule::unique('users', 'email')->ignore($this->editedUser['id']), 'max:255'],
            'editedUser.phone' => ['required', 'string', 'max:255'],
        ];
    }



    public function boot()
    {
        $this->resetEdit();
    }

    private function resetEdit()
    {
        $this->editedUser = [
            'id' => null,
            'name' => null,
            'phone' => null,
            'email' => null,
        ];
    }

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc';
        } else {
            $this->sortDirection = 'asc';
        }
        $this->sortField = $field;
    }

    public function unVerify($userid)
    {
        User::find($userid)->unVerify();
    }

    public function delete($userid)
    {
        $this->emit('userDeleted', $userid);
        User::find($userid)->delete();
        //Redirect::to("/users")->with('success', 'User deleted.');
    }

    public function editUser($userid)
    {
        $user = User::find($userid);
        $this->resetEdit();
        $this->editedUser['id'] = $user->id;
        $this->editedUser['name'] = $user->name;
        $this->editedUser['phone'] = $user->phone;
        $this->editedUser['email'] = $user->email;
    }

    public function saveUser($userid)
    {

        $user = User::find($userid);

        if ($this->editedUser['id'] == $userid) {

            $this->validate();

            (new UpdateUserProfileInformation)->update($user, $this->editedUser);

            $this->resetEdit();

            session()->flash('success', 'Profile successfully updated');

            //Redirect::to("/users")->with('success', 'User info updated.');
        }
    }

    public function render()
    {
        if ($this->sortField === null) {
            $this->sortField = 'id';
        }

        return view('livewire.users', [
            'users' => User::where('name', 'like', '%' . $this->search . '%')
                ->orWhere('email', 'like', '%' . $this->search . '%')
                ->orWhere('phone', 'like', '%' . $this->search . '%')
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate(5)
        ]);
    }
}

resources/views/livewire/terms.blade.php
<div class="space-y-5">

    <div x-data="{ show: false }">

        <x-input.button x-on:click="show = ! show"
            class='w-48 px-3 text-2xl font-bold text-center text-white bg-blue-400 border-0 rounded-lg hover:bg-blue-500'>+ Add new</x-input.button>

        <div x-show="show" style="display: none;" class="flex flex-col w-full p-4 my-3 space-y-2 border border-gray-200 rounded-lg bg-gray-50">
            <div>
                <label class="text-xs" for="newname">Name:</label>
                <x-input.text wire:model="newTerm.name" name="newname" id="newname" class="w-full">
                </x-input.text>
            </div>
            <div>
                <label class="text-xs" for="newbody">Body:</label>
                <x-input.textarea rows="20" wire:model="newTerm.body" name="newbody" id="newbody"></x-input.textarea>
            </div>
            <div class="text-right">
                <x-input.button x-on:click="show = false; newbody.value = newname.value = '';" class="text-xs bg-gray-400 hover:bg-gray-500">Cancel</x-input.button>
                <x-input.button x-on:click="show = false; newbody.value = newname.value = '';" wire:click.prevent="addTerm()" class="text-xs bg-green-400 hover:bg-green-500">Save</x-input.button>
            </div>
        </div>
    </div>

    <div class="relative flex justify-center w-full text-gray-400 focus-within:text-gray-600 align-items: center">
        <div class="absolute transform pointer-events-none top-1/4 left-3">&#x1F50E;</div>
        <input
            class="block w-full px-4 py-3 border border-gray-200 appearance-none rounded-xl form-input pl-14 focus:outline-none"
            type='text' wire:model='search' placeholder="Search terms..." />
    </div>

    <x-table>
        <x-slot name="head">
            <x-table.heading sortable wire:click="sortBy('id')" :direction="$sortField === 'id' ? $sortDirection: null">
                Id</x-table.heading>
            <x-table.heading sortable wire:click="sortBy('name')"
                :direction="$sortField === 'name' ? $sortDirection: null">Name</x-table.heading>
            <x-table.heading sortable wire:click="sortBy('body')"
                :direction="$sortField === 'body' ? $sortDirection: null">Body</x-table.heading>
            <x-table.heading sortable wire:click="sortBy('published_at')"
                :direction="$sortField === 'published_at' ? $sortDirection: null">Published
            </x-table.heading>
            <x-table.heading></x-table.heading>
        </x-slot>
        <x-slot name="body">

            @forelse ($terms as $term)
                <x-table.row wire:loading.class.delay="opacity-50" wire:key="{{ $term->id }}">
                    <x-table.cell class="text-center">
                        {{ $term->id }}
                    </x-table.cell>
                    <x-table.cell>
                        @if (isset($term->id) && $term->id === $editedTerm['id'])
                            <input class="text-xs border-gray-200 border-1 rounded-xl" name='name' type='text'
                                wire:model="editedTerm.name" />
                            @error('editedTerm.name')
                                <div class="absolute text-xs text-red-500 left-2">{{ $message }}</div>
                            @enderror
                        @else
                            {{ $term->name }}
                        @endif
                    </x-table.cell>
                    <x-table.cell>
                        @if (isset($term->id) && $term->id === $editedTerm['id'])
                            <textarea class="w-full text-xs border-gray-200 border-1 rounded-xl" rows="30" name='body'
                                wire:model="editedTerm.body"></textarea>
                            @error('editedTerm.body')
                                <div class="absolute text-xs text-red-500 left-2">{{ $message }}</div>
                            @enderror
                        @else
                            {{ $term->body }}
                        @endif
                    </x-table.cell>
                    <x-table.cell class="font-semibold text-center">
                        @if ($term->published_at)
                            <span
                                class="bg-gray-200 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium leading-4 bg-{{ $term->published_color }}-100 text-{{ $term->published_color }}-800 capitalize">{{ $term->date_for_humans }}</span>
                        @else
                            <span class="px-2 py-1 bg-gray-200 rounded-full">no</span>
                        @endif
                    </x-table.cell>
                    <x-table.cell>
                        <div class="flex-col space-y-2">
                            @if ($term->published_at === null)
                                <div>
                                    <x-input.button wire:click.prevent="publishTerm({{ $term->id }})"
                                        class='w-full text-center bg-orange-500 hover:bg-orange-400'>
                                        Publish
                                    </x-input.button>
                                </div>
                                <div>
                                    @if ($term->id === $editedTerm['id'])
                                        <x-input.button wire:click.prevent="saveTerm({{ $term->id }})"
                                            class='w-full bg-blue-500 hover:bg-blue-400'>
                                            &#128190; Save
                                        </x-input.button>
                                    @else
                                        <x-input.button wire:click.prevent="editTerm({{ $term->id }})"
                                            class='w-full bg-blue-500 hover:bg-blue-400'>
                                            &#128393; Edit
                                        </x-input.button>
                                    @endif
                                </div>
                                <div>
                                    <x-input.button wire:click="delete({{ $term->id }})" class='w-full bg-red-500 hover:bg-red-400'>
                                        &#10008; Delete</x-input.button>
                                </div>
                            @endif
                        </div>
                    </x-table.cell>
                </x-table.row>
            @empty
                <x-table.row>
                    <x-table.cell colspan='5'>
                        <div class="flex items-center justify-center">
                            <span class="py-8 text-xl font-medium text-cool-gray-400">:( No results for
                                {{ $search }}</span>
                        </div>
                    </x-table.cell>
                </x-table.row>
            @endforelse
        </x-slot>
    </x-table>

    <div>
        {{ $terms->links() }}
    </div>
</div>

resources/views/livewire/users.blade.php
<div class="space-y-5">

    <div class="relative flex justify-center w-full text-gray-400 focus-within:text-gray-600 align-items: center">
        <div class="absolute transform pointer-events-none top-1/4 left-3">&#x1F50E;</div>
        <input
            class="block w-full px-4 py-3 border border-gray-200 appearance-none rounded-xl form-input pl-14 focus:outline-none"
            type='text' wire:model='search' placeholder="Search users..." />
    </div>
    <x-table>
        <x-slot name="head">
            <x-table.heading sortable wire:click="sortBy('id')" :direction="$sortField === 'id' ? $sortDirection: null">
                Id</x-table.heading>
            <x-table.heading sortable wire:click="sortBy('name')"
                :direction="$sortField === 'name' ? $sortDirection: null">Name</x-table.heading>
            <x-table.heading sortable wire:click="sortBy('phone')"
                :direction="$sortField === 'phone' ? $sortDirection: null">Phone</x-table.heading>
            <x-table.heading sortable wire:click="sortBy('email')"
                :direction="$sortField === 'email' ? $sortDirection: null">Email</x-table.heading>
            <x-table.heading sortable wire:click="sortBy('email_verified_at')"
                :direction="$sortField === 'email_verified_at' ? $sortDirection: null">Email Confirmed
            </x-table.heading>
            <x-table.heading></x-table.heading>
        </x-slot>
        <x-slot name="body">

            @forelse ($users as $user)
                <x-table.row wire:loading.class.delay="opacity-50" wire:key="{{ $user->id }}"
                    x-on:userDeleted="console.log('deleted' + {{ $user->id }})">
                    <x-table.cell class="text-center">{{ $user->id }}</x-table.cell>
                    <x-table.cell>
                        @if (isset($user->id) && $user->id === $editedUser['id'])
                            <input class="text-xs border-gray-200 border-1 rounded-xl" name='name' type='text'
                                wire:model="editedUser.name" />
                            @error('editedUser.name')
                                <div class="absolute text-xs text-red-500 left-2">{{ $message }}</div>
                            @enderror
                        @else
                            <span>{{ $user->name }}</span>
                        @endif
                    </x-table.cell>
                    <x-table.cell>
                        @if (isset($user->id) && $user->id === $editedUser['id'])
                            <input class="text-xs border-gray-200 border-1 rounded-xl" name='phone' type='tel'
                                wire:model="editedUser.phone" />
                            @error('editedUser.phone')
                                <div class="absolute text-xs text-red-500 left-2">{{ $message }}</div>
                            @enderror
                        @else
                            {{ $user->phone }}
                        @endif
                    </x-table.cell>
                    <x-table.cell>
                        @if (isset($user->id) && $user->id === $editedUser['id'])
                            <input class="text-xs border-gray-200 border-1 rounded-xl" name='email' type='email'
                                wire:model="editedUser.email" />
                            @error('editedUser.email')
                                <div class="absolute text-xs text-red-500 left-2">{{ $message }}</div>
                            @enderror
                        @else
                            {{ $user->email }}
                        @endif
                    </x-table.cell>
                    <x-table.cell>
                        <span
                            class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium leading-4 bg-{{ $user->email_verified_color }}-100 text-{{ $user->email_verified_color }}-800 capitalize">
                            {{ $user->email_verified_at ? $user->date_for_humans : 'Not Yet Verified' }}
                        </span>
                    </x-table.cell>
                    <x-table.cell>
                        <div class="flex-col space-y-2 text-center">
                            <div>
                                @if ($user->id === $editedUser['id'])
                                    <x-input.button wire:click.prevent="saveUser({{ $user->id }})"
                                        class='w-full bg-blue-500 hover:bg-blue-400'>
                                        &#128190; Save
                                    </x-input.button>
                                @else
                                    <x-input.button wire:click.prevent="editUser({{ $user->id }})"
                                        class='w-full bg-blue-500 hover:bg-blue-400'>
                                        &#128393; Edit
                                    </x-input.button>
                                @endif
                            </div>
                            <div>
                                <x-input.button wire:click="delete({{ $user->id }})"
                                    class='w-full bg-red-500 hover:bg-red-400'>
                                    &#10008; Delete</x-input.button>
                            </div>
                            <div>
                                @if ($user->email_verified_at)
                                    <x-input.button wire:click="unVerify({{ $user->id }})"
                                        class='w-full bg-orange-500 hover:bg-orange-400'>
                                        &#128269; Unverify
                                    </x-input.button>
                                @endif
                            </div>
                        </div>
                    </x-table.cell>
                </x-table.row>
            @empty
                <x-table.row>
                    <x-table.cell colspan='6'>
                        <div class="flex items-center justify-center">
                            <span class="py-8 text-xl font-medium text-cool-gray-400">:( No results for
                                {{ $search }}</span>
                        </div>
                    </x-table.cell>
                </x-table.row>
            @endforelse

        </x-slot>
    </x-table>

    <div>
        {{ $users->links() }}
    </div>
</div>